ALTER TABLE deal ADD COLUMN IF NOT EXISTS pickup_time DATETIME NULL;
ALTER TABLE deal ADD COLUMN IF NOT EXISTS reminder_sent TINYINT(1) DEFAULT 0;
ALTER TABLE deal DROP COLUMN IF EXISTS reminder_time;
